# Generated by Django 6.0.6 on 2026-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место выполнения")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("periodicity", models.PositiveIntegerField(default=1, verbose_name="Периодичность (в днях)")),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                ("duration", models.PositiveIntegerField(default=60, verbose_name="Время на выполнение (в секундах)")),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                ("last_reminded", models.DateField(blank=True, null=True, verbose_name="Дата последнего напоминания")),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["id"],
            },
        ),
    ]
