upstream django_app {
    # Ссылаемся на имя будущего Docker-контейнера Django и его порт
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    # Максимальный размер загружаемых файлов (например, картинок к привычкам)
    client_max_body_size 10M;

    # Перенаправление всех запросов на Gunicorn (Django)
    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Папка со статическими файлами Django (стили админки и т.д.)
    location /static/ {
        alias /app/static/;
    }

    # Папка с медиа-файлами пользователей
    location /media/ {
        alias /app/media/;
    }
}
